# -*- coding: utf-8 -*-
"""student_departure_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173hYo6u5e6FgZicmiFynEKgQ-0mkBmKi
"""

# A Student Departure System
students = {}
DEAN_PASSWORD = "neocloud123"

def student_login():
    name = input("Enter your full name: ").strip().title()
    student_id = input("Enter your student ID: ").strip()

    if student_id not in students:
        print("No account found. Creating new student record...")
        students[student_id] = {
            "name": name,
            "exeat_status": "On Campus",
            "history": []
        }
    else:
        print(f"Welcome back, {students[student_id]['name']}!")

    return student_id

def request_exeat(student_id):
    if students[student_id]["exeat_status"] == "Off Campus":
        print("You already have an active exeat. Return first.")
        return

    reason = input("Why are you requesting an exeat? ").strip()
    students[student_id]["exeat_status"] = "Pending Approval"
    students[student_id]["history"].append({"request": reason, "status": "Pending"})
    print("Exeat request submitted. Awaiting dean approval.")

def approve_exeat():
    password = input("Enter dean password: ").strip()
    if password != DEAN_PASSWORD:
        print("Incorrect password.")
        return

    for student_id, info in students.items():
        if info["exeat_status"] == "Pending Approval":
            print(f"\n{info['name']} ({student_id}) requested: {info['history'][-1]['request']}")
            decision = input("Approve? (yes/no): ").strip().lower()
            if decision == "yes":
                info["exeat_status"] = "Off Campus"
                info["history"][-1]["status"] = "Approved"
                print("Approved.")
            else:
                info["exeat_status"] = "On Campus"
                info["history"][-1]["status"] = "Denied"
                print("Denied.")

def return_to_campus(student_id):
    if students[student_id]["exeat_status"] != "Off Campus":
        print("You are not currently out of campus.")
        return

    students[student_id]["exeat_status"] = "On Campus"
    print("Welcome back. You have successfully returned.")

def view_history(student_id):
    print("\nYour Exeat History:")
    for record in students[student_id]["history"]:
        print(f"- {record['request']} → {record['status']}")

def security_view():
    print("\nStudents Currently Off Campus:")
    for student_id, info in students.items():
        if info["exeat_status"] == "Off Campus":
            print(f"- {info['name']} ({student_id})")

def search_student():
    student_id = input("Enter student ID to search: ").strip()
    if student_id in students:
        name = students[student_id]["name"]
        status = students[student_id]["exeat_status"]
        print(f"{name} is currently: {status}")
    else:
        print("Student not found.")

def drive():
    while True:
        print("\n==== Student Departure System (SDS) ====")
        print("1. Student Login")
        print("2. Request Exeat")
        print("3. Return to Campus")
        print("4. View Exeat History")
        print("5. Dean Approval Panel")
        print("6. Security View")
        print("7. Search Student Status")
        print("8. Exit")

        choice = input("Select an option (1-8): ").strip()

        if choice == "1":
            global current_user
            current_user = student_login()
        elif choice == "2":
            request_exeat(current_user)
        elif choice == "3":
            return_to_campus(current_user)
        elif choice == "4":
            view_history(current_user)
        elif choice == "5":
            approve_exeat()
        elif choice == "6":
            security_view()
        elif choice == "7":
            search_student()
        elif choice == "8":
            print("Thank you for using SDS. Goodbye.")
            break
        else:
            print("Invalid choice.")

drive()

